# Generated by Django 3.2.16 on 2023-02-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20230226_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='client',
            name='time_update',
        ),
    ]
