# Generated by Django 3.2.16 on 2023-02-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20230226_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='', upload_to='photo/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='starts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='text',
            field=models.TextField(default=1, max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
