# Generated by Django 3.2.16 on 2023-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20230226_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='static/', verbose_name='Изображение'),
        ),
    ]
